# Generated by Django 4.2.3 on 2023-07-09 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('feedback', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(default='20230709 20:28:32')),
                ('likes', models.ManyToManyField(null=True, related_name='feed_likes', to=settings.AUTH_USER_MODEL)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clothmodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 9, 14, 58, 32, 390460, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('report', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 28, 32, 390460))),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.feedbackmodel')),
            ],
        ),
    ]
