# Generated by Django 4.2.3 on 2023-07-09 15:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0002_alter_feedbackmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='datetime',
            field=models.DateTimeField(default='20230709 20:45:59'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='feed_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 15, 15, 59, 483248, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 45, 59, 483248)),
        ),
    ]
